version = 1

test_patterns = ["test/**"]

exclude_patterns = [
    ".github/**",
    "build/**",
    "docs/**",
    "files/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  ecma_version = "2020"
  module_system = "commonjs"
  environment = ["nodejs"]